# Default values for pathmind-ma.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: 839270835622.dkr.ecr.us-east-1.amazonaws.com/pathmind-ma
  tag: staging
  pullPolicy: Always

service:
  type: NodePort
  port: 8080

env:
  ENVIRONMENT: staging
  S3BUCKET: staging-model-analyzer-static-files.pathmind.com

name: pathmind-ma

namespace: staging

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
#  limits:
#    cpu: 2
#    memory: 2Gi
  requests:
    cpu: 1
    memory: 1Gi


nodeSelector: {}

tolerations: []

affinity: {}

probes:
  readinessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 15
    periodSeconds: 10
    failureThreshold: 10
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 15
