/*
 * This file is generated by jOOQ.
 */
package io.skymind.pathmind.db.jooq;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Sequences {

    /**
     * The sequence <code>public.experiment_id_seq</code>
     */
    public static final Sequence<Long> EXPERIMENT_ID_SEQ = Internal.createSequence("experiment_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.model_id_seq</code>
     */
    public static final Sequence<Long> MODEL_ID_SEQ = Internal.createSequence("model_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.pathmind_user_id_seq</code>
     */
    public static final Sequence<Long> PATHMIND_USER_ID_SEQ = Internal.createSequence("pathmind_user_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.policy_id_seq</code>
     */
    public static final Sequence<Long> POLICY_ID_SEQ = Internal.createSequence("policy_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.project_id_seq</code>
     */
    public static final Sequence<Long> PROJECT_ID_SEQ = Internal.createSequence("project_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.run_id_seq</code>
     */
    public static final Sequence<Long> RUN_ID_SEQ = Internal.createSequence("run_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
