FROM azul/zulu-openjdk:11.0.5

WORKDIR /app

RUN apt-get update -y && \
        apt-get install wget -y && \
        apt-get install rsync -y && \
        wget https://deb.nodesource.com/setup_13.x && \
        bash ./setup_13.x && \
        apt-get update -y && \
        apt-get install nodejs -y && \
        apt-get install maven -y

COPY . .

RUN mvn dependency:go-offline --fail-never

