FROM azul/zulu-openjdk:11.0.5

WORKDIR /app

RUN apt-get update -y && \
        apt-get install wget -y && \
        apt-get install rsync -y && \
        wget https://deb.nodesource.com/setup_14.x && \
        bash ./setup_14.x && \
        apt-get update -y && \
        apt-get install nodejs -y

COPY . .

RUN ./mvnw -ntp dependency:go-offline --fail-never

RUN rm -rf /app/*

