/*
 * This file is generated by jOOQ.
 */
package io.skymind.pathmind.data.db.tables.records;


import io.skymind.pathmind.data.db.tables.ExecutionProviderMetaData;
import org.jooq.*;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExecutionProviderMetaDataRecord extends UpdatableRecordImpl<ExecutionProviderMetaDataRecord> implements Record4<Long, String, String, JSON> {

    private static final long serialVersionUID = -914947791;

    /**
     * Setter for <code>public.execution_provider_meta_data.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.execution_provider_meta_data.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.execution_provider_meta_data.provider_class</code>.
     */
    public void setProviderClass(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.execution_provider_meta_data.provider_class</code>.
     */
    public String getProviderClass() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.execution_provider_meta_data.key</code>.
     */
    public void setKey(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.execution_provider_meta_data.key</code>.
     */
    public String getKey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.execution_provider_meta_data.value</code>.
     */
    public void setValue(JSON value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.execution_provider_meta_data.value</code>.
     */
    public JSON getValue() {
        return (JSON) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, String, JSON> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, String, String, JSON> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ExecutionProviderMetaData.EXECUTION_PROVIDER_META_DATA.ID;
    }

    @Override
    public Field<String> field2() {
        return ExecutionProviderMetaData.EXECUTION_PROVIDER_META_DATA.PROVIDER_CLASS;
    }

    @Override
    public Field<String> field3() {
        return ExecutionProviderMetaData.EXECUTION_PROVIDER_META_DATA.KEY;
    }

    @Override
    public Field<JSON> field4() {
        return ExecutionProviderMetaData.EXECUTION_PROVIDER_META_DATA.VALUE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getProviderClass();
    }

    @Override
    public String component3() {
        return getKey();
    }

    @Override
    public JSON component4() {
        return getValue();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getProviderClass();
    }

    @Override
    public String value3() {
        return getKey();
    }

    @Override
    public JSON value4() {
        return getValue();
    }

    @Override
    public ExecutionProviderMetaDataRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ExecutionProviderMetaDataRecord value2(String value) {
        setProviderClass(value);
        return this;
    }

    @Override
    public ExecutionProviderMetaDataRecord value3(String value) {
        setKey(value);
        return this;
    }

    @Override
    public ExecutionProviderMetaDataRecord value4(JSON value) {
        setValue(value);
        return this;
    }

    @Override
    public ExecutionProviderMetaDataRecord values(Long value1, String value2, String value3, JSON value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExecutionProviderMetaDataRecord
     */
    public ExecutionProviderMetaDataRecord() {
        super(ExecutionProviderMetaData.EXECUTION_PROVIDER_META_DATA);
    }

    /**
     * Create a detached, initialised ExecutionProviderMetaDataRecord
     */
    public ExecutionProviderMetaDataRecord(Long id, String providerClass, String key, JSON value) {
        super(ExecutionProviderMetaData.EXECUTION_PROVIDER_META_DATA);

        set(0, id);
        set(1, providerClass);
        set(2, key);
        set(3, value);
    }
}
