/*
 * This file is generated by jOOQ.
 */
package io.skymind.pathmind.data.db.tables.records;


import io.skymind.pathmind.data.db.tables.ExecutionProviderMetaData;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExecutionProviderMetaDataRecord extends UpdatableRecordImpl<ExecutionProviderMetaDataRecord> implements Record5<Long, Integer, Integer, String, String> {

    private static final long serialVersionUID = -1810143132;

    /**
     * Setter for <code>public.execution_provider_meta_data.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.execution_provider_meta_data.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.execution_provider_meta_data.provider_class</code>.
     */
    public void setProviderClass(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.execution_provider_meta_data.provider_class</code>.
     */
    public Integer getProviderClass() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.execution_provider_meta_data.type</code>.
     */
    public void setType(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.execution_provider_meta_data.type</code>.
     */
    public Integer getType() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.execution_provider_meta_data.key</code>.
     */
    public void setKey(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.execution_provider_meta_data.key</code>.
     */
    public String getKey() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.execution_provider_meta_data.value</code>.
     */
    public void setValue(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.execution_provider_meta_data.value</code>.
     */
    public String getValue() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Integer, Integer, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Integer, Integer, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ExecutionProviderMetaData.EXECUTION_PROVIDER_META_DATA.ID;
    }

    @Override
    public Field<Integer> field2() {
        return ExecutionProviderMetaData.EXECUTION_PROVIDER_META_DATA.PROVIDER_CLASS;
    }

    @Override
    public Field<Integer> field3() {
        return ExecutionProviderMetaData.EXECUTION_PROVIDER_META_DATA.TYPE;
    }

    @Override
    public Field<String> field4() {
        return ExecutionProviderMetaData.EXECUTION_PROVIDER_META_DATA.KEY;
    }

    @Override
    public Field<String> field5() {
        return ExecutionProviderMetaData.EXECUTION_PROVIDER_META_DATA.VALUE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getProviderClass();
    }

    @Override
    public Integer component3() {
        return getType();
    }

    @Override
    public String component4() {
        return getKey();
    }

    @Override
    public String component5() {
        return getValue();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getProviderClass();
    }

    @Override
    public Integer value3() {
        return getType();
    }

    @Override
    public String value4() {
        return getKey();
    }

    @Override
    public String value5() {
        return getValue();
    }

    @Override
    public ExecutionProviderMetaDataRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ExecutionProviderMetaDataRecord value2(Integer value) {
        setProviderClass(value);
        return this;
    }

    @Override
    public ExecutionProviderMetaDataRecord value3(Integer value) {
        setType(value);
        return this;
    }

    @Override
    public ExecutionProviderMetaDataRecord value4(String value) {
        setKey(value);
        return this;
    }

    @Override
    public ExecutionProviderMetaDataRecord value5(String value) {
        setValue(value);
        return this;
    }

    @Override
    public ExecutionProviderMetaDataRecord values(Long value1, Integer value2, Integer value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExecutionProviderMetaDataRecord
     */
    public ExecutionProviderMetaDataRecord() {
        super(ExecutionProviderMetaData.EXECUTION_PROVIDER_META_DATA);
    }

    /**
     * Create a detached, initialised ExecutionProviderMetaDataRecord
     */
    public ExecutionProviderMetaDataRecord(Long id, Integer providerClass, Integer type, String key, String value) {
        super(ExecutionProviderMetaData.EXECUTION_PROVIDER_META_DATA);

        set(0, id);
        set(1, providerClass);
        set(2, type);
        set(3, key);
        set(4, value);
    }
}
