/*
 * This file is generated by jOOQ.
 */
package io.skymind.pathmind.data.db.tables.records;


import io.skymind.pathmind.data.db.tables.Experiment;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExperimentRecord extends UpdatableRecordImpl<ExperimentRecord> implements Record8<Long, String, Long, String, Long, String, LocalDateTime, Integer> {

    private static final long serialVersionUID = 1671105535;

    /**
     * Setter for <code>public.experiment.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.experiment.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.experiment.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.experiment.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.experiment.duration</code>.
     */
    public void setDuration(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.experiment.duration</code>.
     */
    public Long getDuration() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.experiment.reward_function</code>.
     */
    public void setRewardFunction(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.experiment.reward_function</code>.
     */
    public String getRewardFunction() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.experiment.model_id</code>.
     */
    public void setModelId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.experiment.model_id</code>.
     */
    public Long getModelId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.experiment.notes</code>.
     */
    public void setNotes(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.experiment.notes</code>.
     */
    public String getNotes() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.experiment.date_created</code>.
     */
    public void setDateCreated(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.experiment.date_created</code>.
     */
    public LocalDateTime getDateCreated() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.experiment.test_run</code>.
     */
    public void setTestRun(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.experiment.test_run</code>.
     */
    public Integer getTestRun() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, Long, String, Long, String, LocalDateTime, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, Long, String, Long, String, LocalDateTime, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Experiment.EXPERIMENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Experiment.EXPERIMENT.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Experiment.EXPERIMENT.DURATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Experiment.EXPERIMENT.REWARD_FUNCTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Experiment.EXPERIMENT.MODEL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Experiment.EXPERIMENT.NOTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field7() {
        return Experiment.EXPERIMENT.DATE_CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Experiment.EXPERIMENT.TEST_RUN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getDuration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getRewardFunction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getModelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getNotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component7() {
        return getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getTestRun();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getDuration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRewardFunction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getModelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getNotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value7() {
        return getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getTestRun();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperimentRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperimentRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperimentRecord value3(Long value) {
        setDuration(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperimentRecord value4(String value) {
        setRewardFunction(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperimentRecord value5(Long value) {
        setModelId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperimentRecord value6(String value) {
        setNotes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperimentRecord value7(LocalDateTime value) {
        setDateCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperimentRecord value8(Integer value) {
        setTestRun(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperimentRecord values(Long value1, String value2, Long value3, String value4, Long value5, String value6, LocalDateTime value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExperimentRecord
     */
    public ExperimentRecord() {
        super(Experiment.EXPERIMENT);
    }

    /**
     * Create a detached, initialised ExperimentRecord
     */
    public ExperimentRecord(Long id, String name, Long duration, String rewardFunction, Long modelId, String notes, LocalDateTime dateCreated, Integer testRun) {
        super(Experiment.EXPERIMENT);

        set(0, id);
        set(1, name);
        set(2, duration);
        set(3, rewardFunction);
        set(4, modelId);
        set(5, notes);
        set(6, dateCreated);
        set(7, testRun);
    }
}
