/*
 * This file is generated by jOOQ.
 */
package io.skymind.pathmind.data.db.tables.records;


import io.skymind.pathmind.data.db.tables.Model;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModelRecord extends UpdatableRecordImpl<ModelRecord> implements Record9<Long, Long, String, Integer, Integer, String, LocalDateTime, LocalDateTime, byte[]> {

    private static final long serialVersionUID = 1757726848;

    /**
     * Setter for <code>public.model.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.model.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.model.project_id</code>.
     */
    public void setProjectId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.model.project_id</code>.
     */
    public Long getProjectId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.model.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.model.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.model.number_of_observations</code>.
     */
    public void setNumberOfObservations(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.model.number_of_observations</code>.
     */
    public Integer getNumberOfObservations() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.model.number_of_possible_actions</code>.
     */
    public void setNumberOfPossibleActions(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.model.number_of_possible_actions</code>.
     */
    public Integer getNumberOfPossibleActions() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.model.get_observation_for_reward_function</code>.
     */
    public void setGetObservationForRewardFunction(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.model.get_observation_for_reward_function</code>.
     */
    public String getGetObservationForRewardFunction() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.model.date_created</code>.
     */
    public void setDateCreated(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.model.date_created</code>.
     */
    public LocalDateTime getDateCreated() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.model.last_activity_date</code>.
     */
    public void setLastActivityDate(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.model.last_activity_date</code>.
     */
    public LocalDateTime getLastActivityDate() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.model.file</code>.
     */
    public void setFile(byte... value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.model.file</code>.
     */
    public byte[] getFile() {
        return (byte[]) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Long, String, Integer, Integer, String, LocalDateTime, LocalDateTime, byte[]> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Long, String, Integer, Integer, String, LocalDateTime, LocalDateTime, byte[]> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Model.MODEL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Model.MODEL.PROJECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Model.MODEL.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Model.MODEL.NUMBER_OF_OBSERVATIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Model.MODEL.NUMBER_OF_POSSIBLE_ACTIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Model.MODEL.GET_OBSERVATION_FOR_REWARD_FUNCTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field7() {
        return Model.MODEL.DATE_CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field8() {
        return Model.MODEL.LAST_ACTIVITY_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field9() {
        return Model.MODEL.FILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getNumberOfObservations();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getNumberOfPossibleActions();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getGetObservationForRewardFunction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component7() {
        return getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component8() {
        return getLastActivityDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component9() {
        return getFile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getNumberOfObservations();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getNumberOfPossibleActions();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getGetObservationForRewardFunction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value7() {
        return getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value8() {
        return getLastActivityDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value9() {
        return getFile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelRecord value2(Long value) {
        setProjectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelRecord value4(Integer value) {
        setNumberOfObservations(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelRecord value5(Integer value) {
        setNumberOfPossibleActions(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelRecord value6(String value) {
        setGetObservationForRewardFunction(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelRecord value7(LocalDateTime value) {
        setDateCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelRecord value8(LocalDateTime value) {
        setLastActivityDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelRecord value9(byte... value) {
        setFile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ModelRecord values(Long value1, Long value2, String value3, Integer value4, Integer value5, String value6, LocalDateTime value7, LocalDateTime value8, byte[] value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ModelRecord
     */
    public ModelRecord() {
        super(Model.MODEL);
    }

    /**
     * Create a detached, initialised ModelRecord
     */
    public ModelRecord(Long id, Long projectId, String name, Integer numberOfObservations, Integer numberOfPossibleActions, String getObservationForRewardFunction, LocalDateTime dateCreated, LocalDateTime lastActivityDate, byte[] file) {
        super(Model.MODEL);

        set(0, id);
        set(1, projectId);
        set(2, name);
        set(3, numberOfObservations);
        set(4, numberOfPossibleActions);
        set(5, getObservationForRewardFunction);
        set(6, dateCreated);
        set(7, lastActivityDate);
        set(8, file);
    }
}
