/*
 * This file is generated by jOOQ.
 */
package io.skymind.pathmind.data.db.tables.records;


import io.skymind.pathmind.data.db.tables.Policy;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PolicyRecord extends UpdatableRecordImpl<PolicyRecord> implements Record9<Long, Long, String, String, LocalDateTime, LocalDateTime, String, LocalDateTime, Boolean> {

    private static final long serialVersionUID = 916923772;

    /**
     * Setter for <code>public.policy.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.policy.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.policy.run_id</code>.
     */
    public void setRunId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.policy.run_id</code>.
     */
    public Long getRunId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.policy.external_id</code>.
     */
    public void setExternalId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.policy.external_id</code>.
     */
    public String getExternalId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.policy.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.policy.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.policy.started_at</code>.
     */
    public void setStartedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.policy.started_at</code>.
     */
    public LocalDateTime getStartedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.policy.stopped_at</code>.
     */
    public void setStoppedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.policy.stopped_at</code>.
     */
    public LocalDateTime getStoppedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.policy.notes</code>.
     */
    public void setNotes(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.policy.notes</code>.
     */
    public String getNotes() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.policy.exported_at</code>.
     */
    public void setExportedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.policy.exported_at</code>.
     */
    public LocalDateTime getExportedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.policy.has_file</code>.
     */
    public void setHasFile(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.policy.has_file</code>.
     */
    public Boolean getHasFile() {
        return (Boolean) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, Long, String, String, LocalDateTime, LocalDateTime, String, LocalDateTime, Boolean> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, Long, String, String, LocalDateTime, LocalDateTime, String, LocalDateTime, Boolean> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Policy.POLICY.ID;
    }

    @Override
    public Field<Long> field2() {
        return Policy.POLICY.RUN_ID;
    }

    @Override
    public Field<String> field3() {
        return Policy.POLICY.EXTERNAL_ID;
    }

    @Override
    public Field<String> field4() {
        return Policy.POLICY.NAME;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Policy.POLICY.STARTED_AT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Policy.POLICY.STOPPED_AT;
    }

    @Override
    public Field<String> field7() {
        return Policy.POLICY.NOTES;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Policy.POLICY.EXPORTED_AT;
    }

    @Override
    public Field<Boolean> field9() {
        return Policy.POLICY.HAS_FILE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getRunId();
    }

    @Override
    public String component3() {
        return getExternalId();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public LocalDateTime component5() {
        return getStartedAt();
    }

    @Override
    public LocalDateTime component6() {
        return getStoppedAt();
    }

    @Override
    public String component7() {
        return getNotes();
    }

    @Override
    public LocalDateTime component8() {
        return getExportedAt();
    }

    @Override
    public Boolean component9() {
        return getHasFile();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getRunId();
    }

    @Override
    public String value3() {
        return getExternalId();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public LocalDateTime value5() {
        return getStartedAt();
    }

    @Override
    public LocalDateTime value6() {
        return getStoppedAt();
    }

    @Override
    public String value7() {
        return getNotes();
    }

    @Override
    public LocalDateTime value8() {
        return getExportedAt();
    }

    @Override
    public Boolean value9() {
        return getHasFile();
    }

    @Override
    public PolicyRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public PolicyRecord value2(Long value) {
        setRunId(value);
        return this;
    }

    @Override
    public PolicyRecord value3(String value) {
        setExternalId(value);
        return this;
    }

    @Override
    public PolicyRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public PolicyRecord value5(LocalDateTime value) {
        setStartedAt(value);
        return this;
    }

    @Override
    public PolicyRecord value6(LocalDateTime value) {
        setStoppedAt(value);
        return this;
    }

    @Override
    public PolicyRecord value7(String value) {
        setNotes(value);
        return this;
    }

    @Override
    public PolicyRecord value8(LocalDateTime value) {
        setExportedAt(value);
        return this;
    }

    @Override
    public PolicyRecord value9(Boolean value) {
        setHasFile(value);
        return this;
    }

    @Override
    public PolicyRecord values(Long value1, Long value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6, String value7, LocalDateTime value8, Boolean value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PolicyRecord
     */
    public PolicyRecord() {
        super(Policy.POLICY);
    }

    /**
     * Create a detached, initialised PolicyRecord
     */
    public PolicyRecord(Long id, Long runId, String externalId, String name, LocalDateTime startedAt, LocalDateTime stoppedAt, String notes, LocalDateTime exportedAt, Boolean hasFile) {
        super(Policy.POLICY);

        set(0, id);
        set(1, runId);
        set(2, externalId);
        set(3, name);
        set(4, startedAt);
        set(5, stoppedAt);
        set(6, notes);
        set(7, exportedAt);
        set(8, hasFile);
    }
}
