/*
 * This file is generated by jOOQ.
 */
package io.skymind.pathmind.data.db.tables.records;


import io.skymind.pathmind.data.db.tables.PolicySnapshot;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PolicySnapshotRecord extends TableRecordImpl<PolicySnapshotRecord> implements Record2<Long, byte[]> {

    private static final long serialVersionUID = -1263584673;

    /**
     * Setter for <code>public.policy_snapshot.policy_id</code>.
     */
    public void setPolicyId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.policy_snapshot.policy_id</code>.
     */
    public Long getPolicyId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.policy_snapshot.snapshot</code>.
     */
    public void setSnapshot(byte... value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.policy_snapshot.snapshot</code>.
     */
    public byte[] getSnapshot() {
        return (byte[]) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, byte[]> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, byte[]> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return PolicySnapshot.POLICY_SNAPSHOT.POLICY_ID;
    }

    @Override
    public Field<byte[]> field2() {
        return PolicySnapshot.POLICY_SNAPSHOT.SNAPSHOT;
    }

    @Override
    public Long component1() {
        return getPolicyId();
    }

    @Override
    public byte[] component2() {
        return getSnapshot();
    }

    @Override
    public Long value1() {
        return getPolicyId();
    }

    @Override
    public byte[] value2() {
        return getSnapshot();
    }

    @Override
    public PolicySnapshotRecord value1(Long value) {
        setPolicyId(value);
        return this;
    }

    @Override
    public PolicySnapshotRecord value2(byte... value) {
        setSnapshot(value);
        return this;
    }

    @Override
    public PolicySnapshotRecord values(Long value1, byte[] value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PolicySnapshotRecord
     */
    public PolicySnapshotRecord() {
        super(PolicySnapshot.POLICY_SNAPSHOT);
    }

    /**
     * Create a detached, initialised PolicySnapshotRecord
     */
    public PolicySnapshotRecord(Long policyId, byte[] snapshot) {
        super(PolicySnapshot.POLICY_SNAPSHOT);

        set(0, policyId);
        set(1, snapshot);
    }
}
