apiVersion: apps/v1
kind: Deployment
metadata:
  name: trainer-machine-johnny
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trainer-machine-johnny
  template:
    metadata:
      labels:
        app: trainer-machine-johnny
    spec:
      volumes:
      - name: training-machine
        persistentVolumeClaim:
          claimName: training-machine-pvc
      containers:
      - name: trainer-machine-johnny
        volumeMounts:
        - name: training-machine
          mountPath: /var/trainer-machine
        image: 839270835622.dkr.ecr.us-east-1.amazonaws.com/training_machine:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 16
            memory: 32G
          requests:
            cpu: 12
            memory: 28G
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "SPOT-16cpu_32gb"
        effect: "NoSchedule"
      nodeSelector:
        dedicated: SPOT-16cpu_32gb
