apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "policy-deployer.fullname" . }}
rules:
- apiGroups: ["extensions", "apps", "networking.k8s.io", ""] # "" indicates the core API group
  resources: ["deployments","replicasets","pods","secrets","services","ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
