/*
 * This file is generated by jOOQ.
 */
package io.skymind.pathmind.db.jooq.tables.records;


import io.skymind.pathmind.db.jooq.tables.Action;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActionRecord extends UpdatableRecordImpl<ActionRecord> implements Record4<Long, Long, String, Integer> {

    private static final long serialVersionUID = 466994212;

    /**
     * Setter for <code>public.action.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.action.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.action.model_id</code>.
     */
    public void setModelId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.action.model_id</code>.
     */
    public Long getModelId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.action.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.action.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.action.array_index</code>.
     */
    public void setArrayIndex(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.action.array_index</code>.
     */
    public Integer getArrayIndex() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Long, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, Long, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Action.ACTION.ID;
    }

    @Override
    public Field<Long> field2() {
        return Action.ACTION.MODEL_ID;
    }

    @Override
    public Field<String> field3() {
        return Action.ACTION.NAME;
    }

    @Override
    public Field<Integer> field4() {
        return Action.ACTION.ARRAY_INDEX;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getModelId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Integer component4() {
        return getArrayIndex();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getModelId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public Integer value4() {
        return getArrayIndex();
    }

    @Override
    public ActionRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ActionRecord value2(Long value) {
        setModelId(value);
        return this;
    }

    @Override
    public ActionRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public ActionRecord value4(Integer value) {
        setArrayIndex(value);
        return this;
    }

    @Override
    public ActionRecord values(Long value1, Long value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActionRecord
     */
    public ActionRecord() {
        super(Action.ACTION);
    }

    /**
     * Create a detached, initialised ActionRecord
     */
    public ActionRecord(Long id, Long modelId, String name, Integer arrayIndex) {
        super(Action.ACTION);

        set(0, id);
        set(1, modelId);
        set(2, name);
        set(3, arrayIndex);
    }
}
