/*
 * This file is generated by jOOQ.
 */
package io.skymind.pathmind.db.jooq.tables.records;


import io.skymind.pathmind.db.jooq.tables.RewardScore;

import java.math.BigDecimal;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RewardScoreRecord extends TableRecordImpl<RewardScoreRecord> implements Record4<Long, BigDecimal, Integer, Integer> {

    private static final long serialVersionUID = 1350749395;

    /**
     * Setter for <code>public.reward_score.policy_id</code>.
     */
    public void setPolicyId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.reward_score.policy_id</code>.
     */
    public Long getPolicyId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.reward_score.mean</code>.
     */
    public void setMean(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.reward_score.mean</code>.
     */
    public BigDecimal getMean() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>public.reward_score.iteration</code>.
     */
    public void setIteration(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.reward_score.iteration</code>.
     */
    public Integer getIteration() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.reward_score.episode_count</code>.
     */
    public void setEpisodeCount(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.reward_score.episode_count</code>.
     */
    public Integer getEpisodeCount() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, BigDecimal, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, BigDecimal, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return RewardScore.REWARD_SCORE.POLICY_ID;
    }

    @Override
    public Field<BigDecimal> field2() {
        return RewardScore.REWARD_SCORE.MEAN;
    }

    @Override
    public Field<Integer> field3() {
        return RewardScore.REWARD_SCORE.ITERATION;
    }

    @Override
    public Field<Integer> field4() {
        return RewardScore.REWARD_SCORE.EPISODE_COUNT;
    }

    @Override
    public Long component1() {
        return getPolicyId();
    }

    @Override
    public BigDecimal component2() {
        return getMean();
    }

    @Override
    public Integer component3() {
        return getIteration();
    }

    @Override
    public Integer component4() {
        return getEpisodeCount();
    }

    @Override
    public Long value1() {
        return getPolicyId();
    }

    @Override
    public BigDecimal value2() {
        return getMean();
    }

    @Override
    public Integer value3() {
        return getIteration();
    }

    @Override
    public Integer value4() {
        return getEpisodeCount();
    }

    @Override
    public RewardScoreRecord value1(Long value) {
        setPolicyId(value);
        return this;
    }

    @Override
    public RewardScoreRecord value2(BigDecimal value) {
        setMean(value);
        return this;
    }

    @Override
    public RewardScoreRecord value3(Integer value) {
        setIteration(value);
        return this;
    }

    @Override
    public RewardScoreRecord value4(Integer value) {
        setEpisodeCount(value);
        return this;
    }

    @Override
    public RewardScoreRecord values(Long value1, BigDecimal value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RewardScoreRecord
     */
    public RewardScoreRecord() {
        super(RewardScore.REWARD_SCORE);
    }

    /**
     * Create a detached, initialised RewardScoreRecord
     */
    public RewardScoreRecord(Long policyId, BigDecimal mean, Integer iteration, Integer episodeCount) {
        super(RewardScore.REWARD_SCORE);

        set(0, policyId);
        set(1, mean);
        set(2, iteration);
        set(3, episodeCount);
    }
}
