# Default values for trainer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 839270835622.dkr.ecr.us-east-1.amazonaws.com/trainer
  tag: dev
  pullPolicy: Always

#service:
#  type: NodePort
#  port: 80

env:
  SQS_URL: https://queue.amazonaws.com/839270835622/dev-training-queue.fifo
  ENVIRONMENT: dev
  NAME: dev-pathmind.k8s.local
  KOPS_STATE_STORE: s3://dev-pathmind-kops-state/k8s.dev-pathmind.k8s.local
  RL_IMAGE: 839270835622.dkr.ecr.us-east-1.amazonaws.com/rl_training:dev
  

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 2
    memory: 1024Mi
  requests:
    cpu: 1
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}

