apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trainer.fullname" . }}
  labels:
{{ include "trainer.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "trainer.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        timestamp: "{{ date "20060102150405" .Release.Time }}"
      labels:
        app.kubernetes.io/name: {{ include "trainer.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: AWS_DEFAULT_REGION
            value: "us-east-1"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: awsaccesskey
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: awssecretaccesskey
                key: AWS_SECRET_ACCESS_KEY
          - name: ENVIRONMENT
            value: "{{ .Values.env.ENVIRONMENT }}"
          - name: SQS_URL
            value: "{{ .Values.env.SQS_URL }}"
          - name: NAME
            value: "{{ .Values.env.NAME }}"
          - name: KOPS_STATE_STORE
            value: "{{ .Values.env.KOPS_STATE_STORE }}"
          - name: RL_IMAGE
            value: "{{ .Values.env.RL_IMAGE }}"


