apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
{{ include "canary.labels" . | indent 4 }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}

