apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "pathmind-ma.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ include "pathmind-ma.name" . }}
