apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "pathmind-api.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ include "pathmind-api.name" . }}
