apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jenkins.fullname" . }}
  labels:
{{ include "jenkins.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "jenkins.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "jenkins.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: jenkins-storage
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.claimName }}
        - name: docker-graph-storage
          emptyDir: {}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: TESTS_USERNAME
              value: evegeniy@skymind.io
            - name: TESTS_PASSWORD
              value: pw!skymind19
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jenkinspassword
                  key: JENKINSPASSWORD
            - name: JAVA_OPTS
              value: -Dhudson.model.DirectoryBrowserSupport.CSP="sandbox allow-same-origin allow-scripts; default-src 'self'; script-src * 'unsafe-inline'; img-src *; style-src * 'unsafe-inline'; font-src *"
            - name: DOCKER_HOST
              value: tcp://localhost:2375
            - name: S3BUCKET
              value: {{ .Values.env.S3BUCKET }}
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: awsaccesskey
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: awssecretaccesskey
                  key: AWS_SECRET_ACCESS_KEY
            - name: SEGMENT_WEBSITE_KEY
              valueFrom:
                secretKeyRef:
                  name: segmentwebsitekey
                  key: SEGMENT_WEBSITE_KEY
            - name: SEGMENT_SERVER_KEY
              valueFrom:
                secretKeyRef:
                  name: segmentserversitekey
                  key: SEGMENT_SERVER_KEY
            - name: GITHUB_USER
              valueFrom:
                secretKeyRef:
                  name: githubuser
                  key: GITHUB_USER
            - name: GITHUB_SECRET
              valueFrom:
                secretKeyRef:
                  name: githubsecret
                  key: GITHUB_SECRET
          volumeMounts:
            - name: jenkins-storage
              mountPath: /var/jenkins_home
        - name: dind-daemon
          image: "{{ .Values.image2.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              cpu: 20m
              memory: 512Mi
          securityContext:
            privileged: true
          volumeMounts:
          - name: docker-graph-storage
            mountPath: /var/lib/docker
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "jenkins-node"
          effect: "NoSchedule"
      nodeSelector:
        dedicated: jenkins-node
