apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.claimName }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 100Gi

