apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: aws-cleanup-job
spec:
  schedule: "0 */24 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: aws-cleanup-job
            image: 839270835622.dkr.ecr.us-east-1.amazonaws.com/aws_cleanup:latest
            imagePullPolicy: Always
            env:
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: awsaccesskey
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: awssecretaccesskey
                  key: AWS_SECRET_ACCESS_KEY
