apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
 labels:
   name: letsencrypt
 name: letsencrypt
spec:
 acme:
   email: daniel.jaramillo@toptal.com
   http01: {}
   privateKeySecretRef:
     name: letsencrypt
   server: https://acme-v02.api.letsencrypt.org/directory
