/*
 * This file is generated by jOOQ.
 */
package io.skymind.pathmind.db.jooq.tables;


import io.skymind.pathmind.db.jooq.Indexes;
import io.skymind.pathmind.db.jooq.Keys;
import io.skymind.pathmind.db.jooq.Public;
import io.skymind.pathmind.db.jooq.tables.records.ExperimentObservationRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExperimentObservation extends TableImpl<ExperimentObservationRecord> {

    private static final long serialVersionUID = 35976158;

    /**
     * The reference instance of <code>public.experiment_observation</code>
     */
    public static final ExperimentObservation EXPERIMENT_OBSERVATION = new ExperimentObservation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ExperimentObservationRecord> getRecordType() {
        return ExperimentObservationRecord.class;
    }

    /**
     * The column <code>public.experiment_observation.id</code>.
     */
    public final TableField<ExperimentObservationRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('experiment_observation_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.experiment_observation.experiment_id</code>.
     */
    public final TableField<ExperimentObservationRecord, Long> EXPERIMENT_ID = createField(DSL.name("experiment_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.experiment_observation.observation_id</code>.
     */
    public final TableField<ExperimentObservationRecord, Long> OBSERVATION_ID = createField(DSL.name("observation_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>public.experiment_observation</code> table reference
     */
    public ExperimentObservation() {
        this(DSL.name("experiment_observation"), null);
    }

    /**
     * Create an aliased <code>public.experiment_observation</code> table reference
     */
    public ExperimentObservation(String alias) {
        this(DSL.name(alias), EXPERIMENT_OBSERVATION);
    }

    /**
     * Create an aliased <code>public.experiment_observation</code> table reference
     */
    public ExperimentObservation(Name alias) {
        this(alias, EXPERIMENT_OBSERVATION);
    }

    private ExperimentObservation(Name alias, Table<ExperimentObservationRecord> aliased) {
        this(alias, aliased, null);
    }

    private ExperimentObservation(Name alias, Table<ExperimentObservationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ExperimentObservation(Table<O> child, ForeignKey<O, ExperimentObservationRecord> key) {
        super(child, key, EXPERIMENT_OBSERVATION);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.EXPERIMENT_OBSERVATION_PKEY);
    }

    @Override
    public Identity<ExperimentObservationRecord, Long> getIdentity() {
        return Keys.IDENTITY_EXPERIMENT_OBSERVATION;
    }

    @Override
    public UniqueKey<ExperimentObservationRecord> getPrimaryKey() {
        return Keys.EXPERIMENT_OBSERVATION_PKEY;
    }

    @Override
    public List<UniqueKey<ExperimentObservationRecord>> getKeys() {
        return Arrays.<UniqueKey<ExperimentObservationRecord>>asList(Keys.EXPERIMENT_OBSERVATION_PKEY);
    }

    @Override
    public List<ForeignKey<ExperimentObservationRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ExperimentObservationRecord, ?>>asList(Keys.EXPERIMENT_OBSERVATION__PM_FK_EO_EXPERIMENT, Keys.EXPERIMENT_OBSERVATION__PM_FK_EO_OBSERVATION);
    }

    public Experiment experiment() {
        return new Experiment(this, Keys.EXPERIMENT_OBSERVATION__PM_FK_EO_EXPERIMENT);
    }

    public Observation observation() {
        return new Observation(this, Keys.EXPERIMENT_OBSERVATION__PM_FK_EO_OBSERVATION);
    }

    @Override
    public ExperimentObservation as(String alias) {
        return new ExperimentObservation(DSL.name(alias), this);
    }

    @Override
    public ExperimentObservation as(Name alias) {
        return new ExperimentObservation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ExperimentObservation rename(String name) {
        return new ExperimentObservation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ExperimentObservation rename(Name name) {
        return new ExperimentObservation(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
