/*
 * This file is generated by jOOQ.
 */
package io.skymind.pathmind.db.jooq.tables;


import io.skymind.pathmind.db.jooq.Indexes;
import io.skymind.pathmind.db.jooq.Keys;
import io.skymind.pathmind.db.jooq.Public;
import io.skymind.pathmind.db.jooq.tables.records.PolicyRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Policy extends TableImpl<PolicyRecord> {

    private static final long serialVersionUID = 589894250;

    /**
     * The reference instance of <code>public.policy</code>
     */
    public static final Policy POLICY = new Policy();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PolicyRecord> getRecordType() {
        return PolicyRecord.class;
    }

    /**
     * The column <code>public.policy.id</code>.
     */
    public final TableField<PolicyRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.policy.run_id</code>.
     */
    public final TableField<PolicyRecord, Long> RUN_ID = createField(DSL.name("run_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.policy.external_id</code>.
     */
    public final TableField<PolicyRecord, String> EXTERNAL_ID = createField(DSL.name("external_id"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.policy.name</code>.
     */
    public final TableField<PolicyRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.policy.started_at</code>.
     */
    public final TableField<PolicyRecord, LocalDateTime> STARTED_AT = createField(DSL.name("started_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.policy.stopped_at</code>.
     */
    public final TableField<PolicyRecord, LocalDateTime> STOPPED_AT = createField(DSL.name("stopped_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.policy.exported_at</code>.
     */
    public final TableField<PolicyRecord, LocalDateTime> EXPORTED_AT = createField(DSL.name("exported_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.policy.has_file</code>.
     */
    public final TableField<PolicyRecord, Boolean> HAS_FILE = createField(DSL.name("has_file"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field("false", SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.policy.is_valid</code>.
     */
    public final TableField<PolicyRecord, Boolean> IS_VALID = createField(DSL.name("is_valid"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field("true", SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.policy.check_point_file_key</code>.
     */
    public final TableField<PolicyRecord, String> CHECK_POINT_FILE_KEY = createField(DSL.name("check_point_file_key"), SQLDataType.VARCHAR(36), this, "");

    private Policy(Name alias, Table<PolicyRecord> aliased) {
        this(alias, aliased, null);
    }

    private Policy(Name alias, Table<PolicyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.policy</code> table reference
     */
    public Policy(String alias) {
        this(DSL.name(alias), POLICY);
    }

    /**
     * Create an aliased <code>public.policy</code> table reference
     */
    public Policy(Name alias) {
        this(alias, POLICY);
    }

    /**
     * Create a <code>public.policy</code> table reference
     */
    public Policy() {
        this(DSL.name("policy"), null);
    }

    public <O extends Record> Policy(Table<O> child, ForeignKey<O, PolicyRecord> key) {
        super(child, key, POLICY);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.POLICY_RUN_FK_INDEX);
    }

    @Override
    public UniqueKey<PolicyRecord> getPrimaryKey() {
        return Keys.POLICY_PKEY;
    }

    @Override
    public List<UniqueKey<PolicyRecord>> getKeys() {
        return Arrays.<UniqueKey<PolicyRecord>>asList(Keys.POLICY_PKEY, Keys.POLICY_RUN_ID_EXTERNAL_ID_KEY);
    }

    @Override
    public List<ForeignKey<PolicyRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PolicyRecord, ?>>asList(Keys.POLICY__PM_FK_POLICY_RUN);
    }

    private transient Run _run;

    public Run run() {
        if (_run == null)
            _run = new Run(this, Keys.POLICY__PM_FK_POLICY_RUN);

        return _run;
    }

    @Override
    public Policy as(String alias) {
        return new Policy(DSL.name(alias), this);
    }

    @Override
    public Policy as(Name alias) {
        return new Policy(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Policy rename(String name) {
        return new Policy(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Policy rename(Name name) {
        return new Policy(name, null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, Long, String, String, LocalDateTime, LocalDateTime, LocalDateTime, Boolean, Boolean, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }
}
