/*
 * This file is generated by jOOQ.
 */
package io.skymind.pathmind.data.db.tables;


import io.skymind.pathmind.data.db.Indexes;
import io.skymind.pathmind.data.db.Keys;
import io.skymind.pathmind.data.db.Public;
import io.skymind.pathmind.data.db.tables.records.PolicySnapshotRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PolicySnapshot extends TableImpl<PolicySnapshotRecord> {

    private static final long serialVersionUID = -1898510181;

    /**
     * The reference instance of <code>public.policy_snapshot</code>
     */
    public static final PolicySnapshot POLICY_SNAPSHOT = new PolicySnapshot();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PolicySnapshotRecord> getRecordType() {
        return PolicySnapshotRecord.class;
    }

    /**
     * The column <code>public.policy_snapshot.policy_id</code>.
     */
    public final TableField<PolicySnapshotRecord, Long> POLICY_ID = createField(DSL.name("policy_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.policy_snapshot.snapshot</code>.
     */
    public final TableField<PolicySnapshotRecord, byte[]> SNAPSHOT = createField(DSL.name("snapshot"), org.jooq.impl.SQLDataType.BLOB, this, "");

    /**
     * Create a <code>public.policy_snapshot</code> table reference
     */
    public PolicySnapshot() {
        this(DSL.name("policy_snapshot"), null);
    }

    /**
     * Create an aliased <code>public.policy_snapshot</code> table reference
     */
    public PolicySnapshot(String alias) {
        this(DSL.name(alias), POLICY_SNAPSHOT);
    }

    /**
     * Create an aliased <code>public.policy_snapshot</code> table reference
     */
    public PolicySnapshot(Name alias) {
        this(alias, POLICY_SNAPSHOT);
    }

    private PolicySnapshot(Name alias, Table<PolicySnapshotRecord> aliased) {
        this(alias, aliased, null);
    }

    private PolicySnapshot(Name alias, Table<PolicySnapshotRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> PolicySnapshot(Table<O> child, ForeignKey<O, PolicySnapshotRecord> key) {
        super(child, key, POLICY_SNAPSHOT);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.POLICY_SNAPSHOT_POLICY_ID_INDEX, Indexes.POLICY_SNAPSHOT_UNIQUE_POLICY_ID);
    }

    @Override
    public List<UniqueKey<PolicySnapshotRecord>> getKeys() {
        return Arrays.<UniqueKey<PolicySnapshotRecord>>asList(Keys.POLICY_SNAPSHOT_UNIQUE_POLICY_ID);
    }

    @Override
    public List<ForeignKey<PolicySnapshotRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PolicySnapshotRecord, ?>>asList(Keys.POLICY_SNAPSHOT__PM_FK_POLICY_SNAPSHOT_POLICY);
    }

    public Policy policy() {
        return new Policy(this, Keys.POLICY_SNAPSHOT__PM_FK_POLICY_SNAPSHOT_POLICY);
    }

    @Override
    public PolicySnapshot as(String alias) {
        return new PolicySnapshot(DSL.name(alias), this);
    }

    @Override
    public PolicySnapshot as(Name alias) {
        return new PolicySnapshot(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PolicySnapshot rename(String name) {
        return new PolicySnapshot(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PolicySnapshot rename(Name name) {
        return new PolicySnapshot(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, byte[]> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
