# Default values for web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#replicaCount: 2

#image:
#  repository: 949221880207.dkr.ecr.us-east-1.amazonaws.com/top-web
#  tag: stable
#  pullPolicy: Always

service:
  type: NodePort
  port: 80

certificate: letsencrypt-prod

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: persistent
    nginx.ingress.kubernetes.io/session-cookie-name: route
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "7200"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "7200"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: app.pathmind.com
      paths: [/:80:canary]
    - host: devpathmind.com
      paths: [/:80:canary]
    #model analyzer
    - host: ma.devpathmind.com
      paths: [/:8080:pathmind-ma]
    - host: jenkins.devpathmind.com
      paths: [/:8080:jenkins]
    - host: grafana.devpathmind.com
      paths: [/:80:prometheus-operator-grafana]
    - host: kibana.devpathmind.com
      paths: [/:5601:kibana-kb-http]
    - host: pgadmin.devpathmind.com
      paths: [/:80:pgadmin]
    - host: admin.devpathmind.com
      paths: [/:80:pathmind-admin-client]
    - host: admin-server.devpathmind.com
      paths: [/:9091:pathmind-admin-server]
    - host: api.devpathmind.com
      paths: [/:8081:pathmind-api]
    - host: api.pathmind.com
      paths: [/:8081:pathmind-api]

  tls: 
    - secretName: letsencrypt-prod
      hosts:
        - app.pathmind.com
        - devpathmind.com
        - pgadmin.devpathmind.com
        - grafana.devpathmind.com
        - ma.devpathmind.com
        - kibana.devpathmind.com
        - jenkins.devpathmind.com
        - admin.devpathmind.com
        - admin-server.devpathmind.com
        - api.devpathmind.com
        - api.pathmind.com

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

