apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.name }}
  labels:
{{ include "aws-clean-up.labels" . | indent 4 }}
spec:
  schedule: "0 */24 * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            - name: NAME
              value: "{{ .Values.env.NAME }}"
            - name: BUCKET_NAME
              value: "{{ .Values.env.BUCKET_NAME }}"
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: awsaccesskey
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: awssecretaccesskey
                  key: AWS_SECRET_ACCESS_KEY
